CommonBundle\Entity\User:
    repositoryClass: CommonBundle\EntityRepository\UserRepository
    type: entity
    table: admin
    id:
        adminId:
            type: integer
            nullable: false
            unsigned: false
            comment: ID
            id: true
            column: admin_id
            generator:
                strategy: IDENTITY
    fields:
        account:
            type: string
            nullable: false
            length: 256
            fixed: false
            comment: '账号'
        passwd:
            type: string
            nullable: false
            length: 256
            fixed: false
            comment: '密码'
        nickname:
            type: string
            nullable: false
            length: 256
            fixed: false
            comment: '昵称'
        role:
            type: string
            nullable: false
            length: 32
            fixed: false
            comment: '权限'
        createdAt:
            type: datetime
            nullable: false
            comment: '创建时间'
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            comment: '更新时间'
            column: updated_at
        deletedAt:
            type: datetime
            nullable: true
            comment: '删除时间'
            column: deleted_at
    lifecycleCallbacks: {  }
