<?php

namespace CommonBundle\EntityRepository;

use Doctrine\ORM\Query;
use CommonBundle\Entity\Admin;
use CommonBundle\Utils\EntityHelper;
use CommonBundle\Utils\Tool;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepository extends AbstractRepository
{
    /**
     * 管理者リスト
     * @param array $where  検索条件
     * @return array
     */
    public function getAdminList($where = NULL)
    {
        $this->initAdminQuery($where);
        return $this->query->getArrayResult();
    }

    /**
     * init query
     */
    public function initAdminQuery($where = NULL)
    {
        $this->query = $this->createQueryBuilder('a')
        ->select('a.adminId, a.account, a.nickname, a.role, a.createdAt, a.updatedAt')
        ->where("a.deletedAt IS NULL");
        if ($where && is_array($where)) {
            foreach ($where as $key => $value) {
                $this->addWhereToQuery($key, $value);
            }
        }
    }
    
    public function addWhereToQuery($key, $value){
        if ($key!==null && $value!==null) {
            switch ($key) {
                case 'offset':
                    $this->query->setFirstResult($value);
                    break;
                case 'max':
                    $this->query->setMaxResults($value);
                    break;
                default :
                    break;
            }
        }
    }

}
