<?php

namespace CommonBundle\EntityRepository;

use Doctrine\ORM\EntityRepository;
use CommonBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends AbstractRepository
{
    public function getPostList()
    {
        $queryBuilder = $this->createQueryBuilder('p')
        ->select("p.postId, p.title, p.content, p.createdAt, p.updatedAt")
        ->where("p.deletedAt IS NULL");
        $postList = $this->getArrayResult($queryBuilder);
        return $postList;
    }
}
